### ISSUE TITLE
Bug in after upload avatars

### ISSUE THREAD

**Issue by inrussiawithhate** [brunnopleffken/addictive-community#85] opened 2016-04-16 21:45 UTC
Hello, when I upload an avatar and I click somewhere on your profile or anywhere else refers to me / controllers/my username/

Warning: require(controllers/Hated.php): failed to open stream: No such file or directory in C:\xampp\htdocs\index.php on line 132

Fatal error: require(): Failed opening required 'controllers/Hated.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\index.php on line 132

**Comment by inrussiawithhate** [comment] 2016-04-16 21:56
And what is this...? May be bug? :)

![what](https://cloud.githubusercontent.com/assets/7196689/14583841/41576b74-0437-11e6-87cf-15e8d1d78f03.jpg)

**Comment by zalexstudios** [comment] 2016-04-17 02:10
View the settings of your server! C:\xampp
I tried to save on hosting, it works!

**Comment by brunnopleffken** [comment] 2016-04-17 19:38
Wait, you're posting about two different things... Let's do it by steps!

1. Check the settings of your community and see if the absolute path is correct. If the paths (both URL as absolute path) is incorrect, then the images will be brought incorrectly.
2. In the image, this is a redirect forum. In this field (where it says "Hated"), should be the URL to where the room will redirect.

**Comment by inrussiawithhate** [comment] 2016-04-19 11:02
When added forum in Cyrillic and open it ... Displays the error. How do I stop mod_rewrite forums to work everything right ...

**Comment by brunnopleffken** [comment] 2016-04-19 17:27
The only place where Unicode characters are used in URL Rewrite is in threads (this were fixed in #74)... When accessing rooms, the URL remains `/room/[id]`, so, being English or Russian, everything should work fine... I think the source of the problem is other...

So I made a test, as seen below:

<img width="1280" alt="screen shot 2016-04-19 at 14 22 37" src="https://cloud.githubusercontent.com/assets/3427344/14648752/360a8684-063a-11e6-9969-29b10e027312.png">

I tried to create several rooms with different non-latin characters (using Google Translator, obviously 😛 ), so these are Greek, Hindi and Korean threads. Everything works fine! Even in the database:

<img width="535" alt="screen shot 2016-04-19 at 14 25 36" src="https://cloud.githubusercontent.com/assets/3427344/14648834/a1b2ab32-063a-11e6-9652-4c8309f5ef9f.png">

So, this is not a Unicode issue...

**Closed** 2016-12-23 23:24 UTC
Labels: not reproducible
